### ISSUE TITLE
Add WoW Arbitrage Search Page

### ISSUE THREAD

**Issue by cohenaj194** [ff14-advanced-market-search/saddlebag-with-pockets#104]
We have a new api up and we should build a page around it:

url: `http://api.saddlebagexchange.com/api/wow/scan`
json body: 
```
{
    "homeRealmId": 61,
    "newRealmId": 3678,
    "min_historic_price": 10000,
    "desired_roi": 50,
    "sale_per_day": 0
}
```
The users decide the price, roi and sales inputs.  The Realm Id's are determined from a list, I have made the first list here: 

https://gist.githubusercontent.com/cohenaj194/0b59e7c719678dbbe6e49d856680c3c0/raw/0d645e8a22d76bc88692404680e0d58889a6474b/wow-server-name-to-id.json

Users will pick server names from the keys of that json in the ui, then react can change that into the correct int.  How it works in WoW is that multiple servers share the same market in a "connected realm."  Thats why a lot of servers share the same realm id with a bunch of others. 

We should hardcode that json data into saddlebag somewhere. 

_____

The response will be 4 values in the json, all will be lists:
- out_of_stock
- out_w_sales
- profit_w_sales
- profitable_items

The `w_sales` may or may not be empty, if you try a very low min price or roi you may get some.
- `out_w_sales` is the same syntax as `out_of_stock` data.
- `profit_w_sales` is the same syntax as `profitable_items` data.

Output example:
```
{
    "out_of_stock": [
        {
            "historicPrice": 9999999.99,
            "itemID": 6198,
            "name": "Jurassic Wristguards",
            "price": 8999999.64,
            "salesPerDay": 0
        },
        {
            "historicPrice": 9999999.99,
            "itemID": 36687,
            "name": "Illuminated Scepter",
            "price": 43219.69,
            "salesPerDay": 0
        },
        {
            "historicPrice": 9999999.99,
            "itemID": 55604,
            "name": "Frayfeather Helm",
            "price": 401507.97,
            "salesPerDay": 0
        },
        {
            "historicPrice": 9461484.52,
            "itemID": 55721,
            "name": "Galardell Robe",
            "price": 520676.95,
            "salesPerDay": 0
        },
        {
            "historicPrice": 8694444.01,
            "itemID": 49282,
            "name": "Big Battle Bear",
            "price": 5666666.0,
            "salesPerDay": 0
        },
        {
            "historicPrice": 6130937.01,
            "itemID": 4476,
            "name": "Beastwalker Robe",
            "price": 6888118.03,
            "salesPerDay": 0
        },
        {
            "historicPrice": 4000000.0,
            "itemID": 20030,
            "name": "Pet Rock",
            "price": 2222222.24,
            "salesPerDay": 0
        },
        {
            "historicPrice": 3180099.0,
            "itemID": 23476,
            "name": "Squire's Shirt",
            "price": 9999999.99,
            "salesPerDay": 0
        },
        {
            "historicPrice": 2718347.26,
            "itemID": 20673,
            "name": "Abyssal Plate Girdle",
            "price": 3322911.61,
            "salesPerDay": 0
        },
        {
            "historicPrice": 1500000.01,
            "itemID": 18665,
            "name": "The Eye of Shadow",
            "price": 499999.01,
            "salesPerDay": 0
        },
        {
            "historicPrice": 1495347.25,
            "itemID": 18704,
            "name": "Mature Blue Dragon Sinew",
            "price": 500000.0,
            "salesPerDay": 0
        },
        {
            "historicPrice": 1369082.365,
            "itemID": 2166,
            "name": "Foreman's Leggings",
            "price": 1414627.91,
            "salesPerDay": 0
        },
        {
            "historicPrice": 1300000.0,
            "itemID": 6139,
            "name": "Novice's Robe",
            "price": 9999999.99,
            "salesPerDay": 0
        },
        {
            "historicPrice": 1124707.0,
            "itemID": 18360,
            "name": "Harnessing Shadows",
            "price": 9999999.01,
            "salesPerDay": 0
        },
        {
            "historicPrice": 1054534.415,
            "itemID": 97826,
            "name": "Latent Kor'kron Chestpiece",
            "price": 2654377.75,
            "salesPerDay": 0
        },
        {
            "historicPrice": 1013010.165,
            "itemID": 2105,
            "name": "Thug Shirt",
            "price": 7444132.04,
            "salesPerDay": 0
        },
        {
            "historicPrice": 1010191.645,
            "itemID": 97831,
            "name": "Latent Kor'kron Spaulders",
            "price": 1832349.23,
            "salesPerDay": 0
        }
    ],
    "out_w_sales": [],
    "profit_w_sales": [],
    "profitable_items": [
        {
            "historicPrice": 9999999.99,
            "home_price": 95000.0,
            "itemID": 55379,
            "name": "Sorrowmurk Crystal",
            "new_price": 9999999.99,
            "profit": 9404999.9905,
            "roi": 98,
            "salesPerDay": 0
        },
        {
            "historicPrice": 7636375.895,
            "home_price": 3000000.0,
            "itemID": 13519,
            "name": "Recipe: Flask of the Titans",
            "new_price": 9999999.99,
            "profit": 6499999.990499999,
            "roi": 68,
            "salesPerDay": 0
        },
        {
            "historicPrice": 6109286.385,
            "home_price": 3423380.6,
            "itemID": 36603,
            "name": "Archaic Longspear",
            "new_price": 9999999.99,
            "profit": 6076619.3905,
            "roi": 63,
            "salesPerDay": 0
        },
        {
            "historicPrice": 1765297.78,
            "home_price": 400000.0,
            "itemID": 4448,
            "name": "Husk of Naraxis",
            "new_price": 2727786.68,
            "profit": 2191397.346,
            "roi": 84,
            "salesPerDay": 0
        },
        {
            "historicPrice": 1097388.9775,
            "home_price": 40000.0,
            "itemID": 36615,
            "name": "Expert's Longbow",
            "new_price": 1586178.96,
            "profit": 1466870.012,
            "roi": 97,
            "salesPerDay": 0
        },
        {
            "historicPrice": 1066274.0675,
            "home_price": 500000.01,
            "itemID": 38089,
            "name": "Ruby Shades",
            "new_price": 1500000.0,
            "profit": 924999.99,
            "roi": 64,
            "salesPerDay": 0
        }
    ]
}
```

**Comment by oldben87** [comment]
What is the purpose of each of these 4 results?

Does anything benefit being the top result to display?

**Comment by cohenaj194** [comment]
Lets also get 2 link columns in there.  There are 2 websites we can use that ItemID for. https://www.wowhead.com/item=177062 and https://oribos.exchange/#us-area-52/177062
wowhead should be easy its just sticking the item id in there, its more info on an item 
oribos basically is an exact online copy of the wow auction house so it lets people see what the ah would be like

**Comment by cohenaj194** [comment]
> What is the purpose of each of these 4 results?
> 
> Does anything benefit being the top result to display?

Everything should be auto sorted we just need to display it.  In wow its the reverse of FFXIV, here we can buy from the home server but only sell on the new server: 

- `out_of_stock` is sorted by `historicPrice` it shows items listed on the home server and not listed on the new server.  This means you can sell it for any price.
- `profitable_items` are listed on the new server buy are cheaper to buy on the home server.   They are sorted by how much profit you can make by selling on the new server after buying from the old one.

**Comment by cohenaj194** [comment]
@oldben87 let me know if this is something we can do in the FE or you would prefer I do it with the API

For oribos.exchange links like `https://oribos.exchange/#us-area-52/177062` we need to include the server name.  The server name will be the link with all spaces and non alpha numeric characters replaced by dashes `https://oribos.exchange/#us-{SERVER_NAME}/{ITEM_ID}`.  We should do this for both new and old servers. However we can bump this to a new issue if it may take some time.

**Comment by oldben87** [comment]
The WoWHeadlink I think is ok, not too sure about the other one purely as I noticed there are sometimes several regions per server, like Deathwind has a EU, US and KR region. How should we handle that?

**Comment by cohenaj194** [comment]
Right now everything is US only

**Comment by oldben87** [comment]
Ok, so each server also shares it's ID with another, does it matter if they see an option they may or may not have selected?

**Comment by oldben87** [comment]
Also this server appears to be EU only so the link won't work if we assume everything is US?
https://oribos.exchange/#eu-throkferoth/184505
