### ISSUE TITLE
Per page analytics 

### ISSUE THREAD

**Issue by cohenaj194** [ff14-advanced-market-search/saddlebag-with-pockets#133]
I want to be able to see which pages the users are going to, what is being used the most, where they are from. 

That way we can better target our market.  It took way too long to realize no one in china uses our stuff so I have disabled that.

**Comment by Acen** [comment]
https://analytics.google.com/analytics/web/#/analysis/p314676254/edit/NhXsU5L9SLq-dr0mgw0R5w

**Comment by Acen** [comment]
https://analytics.google.com/analytics/web/#/p314676254/reports/explorer?params=_u..nav%3Dmaui%26_r.explorerCard..seldim%3D%5B%22country%22,%22unifiedPagePathScreen%22%5D&r=user-demographics-detail&ruid=user-demographics-detail,user,demographics&collectionId=user
