### ISSUE TITLE
Export Search

### ISSUE THREAD

**Issue by cohenaj194** [ff14-advanced-market-search/saddlebag-with-pockets#145]
Heres a new search it compares the minimum prices of items on multiple servers at once. 

This is for people with alts on lots of servers that have many options where to sell an item that they have.  They want to know what servers their items will be worth the most on so we get the minimum prices for a few different items at once.

http://api.saddlebagexchange.com/api/export

api post body
```
  {
    "home_server": "Famfrit", 
    "export_servers": ["Lamia","Seraph"],
    "item_ids": [33275,4745],
    "hq_only": false
  }
```

result example ( if the price is 0 then it means the item is out of stock)
```
{
    "33275": {
        "Famfrit": 147000,
        "Lamia": 344400,
        "Seraph": 0
    },
    "4745": {
        "Famfrit": 63,
        "Lamia": 52,
        "Seraph": 73
    }
}
```

**Comment by oldben87** [comment]
Is there any chance of turning the response into a list which has the itemId as a property in the object?

**Comment by oldben87** [comment]
@cohenaj194 
On the sidebar there are going to be lots of buttons under the FF14 section, would it be worth looking over the buttons and grouping them differently?
