### ISSUE TITLE
cleanup olivias searches

### ISSUE THREAD

**Issue by cohenaj194** [ff14-advanced-market-search/saddlebag-with-pockets#147]
ref https://github.com/ff14-advanced-market-search/saddlebag-with-pockets/pull/146#discussion_r1038638245

Olivia gave me 11 new searches and naming is hard especially when theres alot of manual copying and pasting on my part

also separating it out now into the following sections in the future or new tabs may be good: Saddlebag Searches, Olivias Low Cost Investment, Olivias Medium Cost Investment, and Olivias High Cost Investment

**Comment by oldben87** [comment]
I think it might be worth refactoring how we do the queries, then people can make custom ones and share them as url links:

`saddlebag.com/queries/full-scan?homeServerId=2&roi=50 ...`
This will enable us to read these on the form page, and people can search that way.

We might need to refactor the redux store to instead store the last 10 searches or something so people can still see their previous searches.

This will also make it easier for people to share around links and customise their own search results.
We can make a 'copylink to clipboard' button to make it easier for users.
