### ISSUE TITLE
oribos link is us instead of eu

### ISSUE THREAD

**Issue by cohenaj194** [ff14-advanced-market-search/saddlebag-with-pockets#182]
for some reason the EU links to oribos now have the us link instead of the eu link

even when i go in and save this in the site settings from North america to Europe its always the us link

**Comment by oldben87** [comment]
It has always been this way!

Just fyi
https://github.com/ff14-advanced-market-search/saddlebag-with-pockets/issues/104#issuecomment-1295498199
