### ISSUE TITLE
FFXIV undercut alerts generator: add option to add -1 to ignore ids

### ISSUE THREAD

**Issue by cohenaj194** [ff14-advanced-market-search/saddlebag-with-pockets#188]
So we have a new feature that changes FFXIV undercut behavior without changing the api at all.  

If a user only wants to be alerted on items they put in the `add_ids` then you need to put `-1` in the ignore ids.  For example the following will only alert on the item with ids `2` or `38955` and will ignore all others. 

```
{
  "seller_id": "foobar",
  "server": "Jenova",
  "add_ids": [2, 38955],
  "ignore_ids": [-1],
  "hq_only": false
}
```

So we just need an extra button that will put `-1` into `ignore_ids` if a user only wants to be alerted on items added to `add_ids`

So the idea is to change this form 
<img width="881" alt="image" src="https://user-images.githubusercontent.com/17516896/213280919-963e2f5f-a4cf-4ce0-8ba9-d95c00e42ed9.png">

If a user has added something to the `add_ids` list then we give them the option to `ignore all items except those on your important items list`

Because if a user ignores all items except the ones on the `add_ids` and the `add_ids` is empty then they will get no alerts. 

Alternatively the easy way is a checkbox that says `Only alert on important items` and when its selected it adds `-1` to `ignore_ids`.

**Comment by oldben87** [comment]
I think our problem is that this alert isn't straight forward.

A user can be in 2 states:
Alert on everything - filter out any items in my ignore Ids.
Alert on specific items - only alert on these items I specify.

We should refactor the form so it is clearer what is going on.
