### ISSUE TITLE
update ffxiv undercut form with "ignore_data_after_hours"

### ISSUE THREAD

**Issue by cohenaj194** [ff14-advanced-market-search/saddlebag-with-pockets#204]
I have added a new value to undercuts "ignore_data_after_hours" which ignores data that is old, it also works if you dont add this in just so the current setup is fine for now and it doesnt break the stuff already in the db

For example this ignores any data older than 24 hours

```
{
    "server": "Louisoix", 
    "add_ids": [], 
    "hq_only": false, 
    "seller_id": "foobaradsfpuauahldf", 
    "ignore_ids": [],
    "ignore_data_after_hours": 24
}
```

@oldben87 lets add a new option that by default adds something to the form so that the field can be changed by users in the website, make the default something super high like 10000 hours

**Comment by oldben87** [comment]
10000 hours is like 14 months? Do we want a more sensible default like 30 days?
