### ISSUE TITLE
ignore_undercuts_with_quantity_over for ffxiv undercuts

### ISSUE THREAD

**Issue by cohenaj194** [ff14-advanced-market-search/saddlebag-with-pockets#221]
for undercuts too i added a new option 
```
    {
      "seller_id": "5d974f95bf1527230170dd257095e25ecbaf8bc088a329db6a89dbf095233814",
      "server": "Leviathan",
      "add_ids": [],
      "ignore_ids": [],
      "hq_only": true,
      "ignore_data_after_hours": 24,
      "ignore_undercuts_with_quantity_over": 40
    }
```
`ignore_undercuts_with_quantity_over` ignores big stacks of ffxiv commodities as some players only feel they are being undercut if the stack is about the same size and cost as their own.
it should max out at 9999

**Comment by oldben87** [comment]
What should the default for this be?
 
What is the "I don't care about this" option?
