### ISSUE TITLE
RemixV2: CatchBoundary & ErrorBoundary updates

### ISSUE THREAD

**Issue by Acen** [ff14-advanced-market-search/saddlebag-with-pockets#260]
https://remix.run/docs/en/main/pages/v2#catchboundary-and-errorboundary

**Comment by oldben87** [comment]
@Acen 

We might not need to do this, don't believe we use the CatchBoundary anywhere in the codebase

**Comment by Acen** [comment]
Yar, was just a mention from reading the v2 changelog.
