### ISSUE TITLE
wow export search

### ISSUE THREAD

**Issue by cohenaj194** [ff14-advanced-market-search/saddlebag-with-pockets#279]
ref https://github.com/ff14-advanced-market-search/saddlebag-with-pockets/issues/253

`http://{{LOCAL}}/api/wow/export`

you can try this out with 2 items for `194018` and `3390` legacy support is incomming

```
{
    "region": "NA",
    "itemID": 194018,
    "populationWP": 1,
    "populationBlizz": 1,
    "rankingWP": 90,
    "minPrice": 1000,
    "maxQuantity": 1000,
    "sortBy": "minPrice",
    "connectedRealmIDs": {}
}
```

regular item example: 
[test1.json.zip](https://github.com/ff14-advanced-market-search/saddlebag-with-pockets/files/11941641/test1.json.zip)

pet example (its the same except the warcraft pets link is not an empty string)

[test2.json.zip](https://github.com/ff14-advanced-market-search/saddlebag-with-pockets/files/11941645/test2.json.zip)

@oldben87 let me know if this makes more sense

**Comment by oldben87** [comment]
Are the all links meant to be the same for all the responses from the api?

<img width="1123" alt="Screenshot 2023-07-03 at 23 43 59" src="https://github.com/ff14-advanced-market-search/saddlebag-with-pockets/assets/51456734/b09090a3-e165-4428-9a3d-3641b98256e7">

**Comment by oldben87** [comment]
> Only the Undermine link is important as that is different for each server.

They are all the same at the moment
