### ISSUE TITLE
FFXIV Crafting Shopping list json generator

### ISSUE THREAD

**Issue by cohenaj194** [ff14-advanced-market-search/saddlebag-with-pockets#289]
Similar to craftsim this one takes input for one api, then that api does recipe lookups and provides data for the 2nd api

- `http://{{PROD}}/api/createshoppinglist`
- `http://{{PROD}}/api/shoppinglist`

[this guide explains how to use it](https://github.com/ff14-advanced-market-search/saddlebag-with-pockets/wiki/Temp-%E2%80%90-How-to-use-FFXIV-Shopping-List)

# 1st api

this lets users pick what they want to make, how much to make, and what job they want to use to make it

`http://{{PROD}}/api/createshoppinglist`

Need a webform that can produce this data by searching the ffxiv item names and letting users create a shopping list for the ingredients of items they want to craft. This should work similar to the price alert input or other pages like that

post data

```
{
    "home_server": "Famfrit",
    "shopping_list": [
        {"itemID": 15157, "craft_amount": 11, "hq": false, "job": 8},
        {"itemID": 30835, "craft_amount": 11, "hq": true, "job": 8},
        {"itemID": 38549, "craft_amount": 11, "hq": true, "job": 8},
        {"itemID": 33275, "craft_amount": 11, "hq": false, "job": 8},

        {"itemID": 39482, "craft_amount": 11, "hq": false, "job": 10},
        {"itemID": 39687, "craft_amount": 11, "hq": true, "job": 10},
        {"itemID": 39667, "craft_amount": 11, "hq": true, "job": 10}
    ]
}
```

# 2nd api

That will then give the post data for the 2nd api, the important one here is the `crafting_list` which contains the keys of the items to craft and the required materials along with how much of the item the user wants to craft

`http://{{PROD}}/api/shoppinglist`

```
{
    "crafting_list": {
        "15157": {
            "craft_amount": 11,
            "hq": {},
            "nq": {
                "15": 1,
                "16": 1,
                "5336": 3,
                "5379": 3,
                "7017": 5,
                "7772": 5
            }
        },
        "30835": {
            "craft_amount": 11,
            "hq": {
                "19928": 2,
                "19929": 3,
                "19948": 2
            },
            "nq": {
                "10": 7,
                "16733": 5,
                "24003": 1,
                "9": 7
            }
        }
    ],
    "home_server": "Famfrit"
}
```

# final table output

the final output then goes in a table, theres also 2 other values for `average_cost_per_craft` and `total_cost` which should be displayed

```
{
    "average_cost_per_craft": 285163,
    "data": [
        {
            "hq": true,
            "itemID": 39723,
            "name": "Grade 8 Dexterity Alkahest",
            "pricePerUnit": 4200,
            "quantity": 16,
            "worldName": "Adamantoise - Aether"
        },
        {
            "hq": true,
            "itemID": 39723,
            "name": "Grade 8 Dexterity Alkahest",
            "pricePerUnit": 4200,
            "quantity": 3,
            "worldName": "Adamantoise - Aether"
        },
        {
            "hq": true,
            "itemID": 39723,
            "name": "Grade 8 Dexterity Alkahest",
            "pricePerUnit": 4200,
            "quantity": 3,
            "worldName": "Adamantoise - Aether"
        },
        {
            "hq": true,
            "itemID": 39723,
            "name": "Grade 8 Dexterity Alkahest",
            "pricePerUnit": 4200,
            "quantity": 3,
            "worldName": "Adamantoise - Aether"
        },
        .....
        {
            "hq": false,
            "itemID": 27951,
            "name": "Dancing Wing",
            "pricePerUnit": 573299,
            "quantity": 1,
            "worldName": "Zalera - Crystal"
        }
    ],
    "total_cost": 21957626
}
```

**Comment by oldben87** [comment]
any more info on this?
Is it to create a json for copy paste or generate a file?
What is a job?
How do we know the craft amount?

**Comment by oldben87** [comment]
Is there a list of specific craftable items, or is any item craftable?

The current item picker does not have the data to filter out craftable / non-craftable items
