### ISSUE TITLE
BUG: need to have 2 options for allagan-data columns 

### ISSUE THREAD

**Issue by cohenaj194** [ff14-advanced-market-search/saddlebag-with-pockets#294]
It seems allagan tools is now also showing the option `total quantity available` instead of `quantity` and `inventory location` instead of `location`

The api works with both and we need the frontend to just accept the other column names as being acceptable 

New plugin columns 
![image](https://github.com/ff14-advanced-market-search/saddlebag-with-pockets/assets/17516896/0509e3c5-d369-47fe-a9c4-4de565ce07fe)

Old column names
![image0](https://github.com/ff14-advanced-market-search/saddlebag-with-pockets/assets/17516896/80cc65ec-089a-4520-805b-9f9fe0764a41)

**Comment by oldben87** [comment]
Can you provide an example of both valid data input options? I forget how this works 😅
