### ISSUE TITLE
Quick-Fill Search parameters

### ISSUE THREAD

**Issue by cohenaj194** [ff14-advanced-market-search/saddlebag-with-pockets#3]
Add some buttons to pre-fill some recommended query variables, put em on the query page like this: 

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/17516896/190889508-8e11a799-2200-4efb-8373-796807419c25.png">

Then when you click on one they all do the same /api/scan operation just wit different values:

Additional Detail: https://github.com/ff14-advanced-market-search/saddlebag.exchange/issues/54

1) High Value Search (sort by profit amt)

<img width="1114" alt="image" src="https://user-images.githubusercontent.com/17516896/188286397-df4d5a41-8b37-4da5-acdb-3433dfbd1e06.png">

2) Fast Sale Rate Search (sort by sale rate)

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/17516896/188286474-bec1194b-c67e-49e2-9590-360c9c017d5d.png">

3.) Commodities Search (say this is anything that is sold in stacks of more than 1 and has almost no wearable gear)(sort by sale rate)
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/17516896/188286580-fbbbf8ab-ed41-44de-9780-fd9174934bf5.png">

4) NPC Vendor Item Search (sort by profit amt)

<img width="985" alt="image" src="https://user-images.githubusercontent.com/17516896/188286681-f642a758-fa32-40dd-aa76-9a2f2bd0db27.png">

5) Beginner Out of Stock Search 

- (also include that its low level requirement, low risk, low price, low effort, low competition, high profit margins, but slow sale rates) 
- (tell them this works when you buy multiple different cheap items that are out of stock on your servers market board but can be purchased for under 3k (the best ones can be found for less than 200gil) and sell them for around 70,000 to 100,000 gil. Almost anything will sell for that price range.  Not everything is guaranteed to sell before competition shows up, so its best when selling 5 or more different kinds of out of stock items at once. If one kind of item doesn't sell, it doesn't matter because you only need 1 or 2 sales to make a profit)
- (auto sort by lowest price) 
- (link to a webpage with tutorial links)(link to [the old tutorial](https://www.youtube.com/watch?v=KWMwuEO31Og) for now, then we will switch when the new one is up)
- (add a note telling people to make sure to double check universalis and their local marketboard before buying, data in our system or universalis may be out of date if no one has check the marketboard recently, to update data please search the marketboard with [dalamud plugins ffxiv](https://goatcorp.github.io/) installed)

<img width="832" alt="image" src="https://user-images.githubusercontent.com/17516896/188775031-0697a3f3-290a-48ed-80e1-e2f64a521469.png">

7) Low Quality Out of Stock

<img width="834" alt="image" src="https://user-images.githubusercontent.com/17516896/190919089-e7779e59-793a-4253-bb3d-6600feb5ea27.png">

- Search for out of stock NQ with "filters": [ -3, -2, 1, 2, 3, 4, 7], basically searching all NQ stuff except for `Materials` and `Meals and Medicine`.

**Comment by cohenaj194** [comment]
Heres the code blob I used to make the buttons from https://github.com/ff14-advanced-market-search/saddlebag-with-pockets/blob/devtest/app/routes/index.tsx

The important part here is the descriptions

```
const recommendedQueries = [
    {
        name:        'Full Scan',
        description: "Search throughout the entire data set! Nigh-infinite options.",
        icon:        DocumentSearchIcon,
        href:        '/queries/full-scan',
    },
    {
        name:        'High Value Scan',
        description: "Search for high value trades.",
        icon:        DocumentSearchIcon,
        href:        '/queries/full-scan',
    },
    {
        name:        'Fast Sales Scan',
        description: "Search for items with high rate of sales.",
        icon:        DocumentSearchIcon,
        href:        '/queries/full-scan',
    },
    {
        name:        'Commodities Scan',
        description: "Search for items that sell in larger stack sizes (i.e. larger quantities)",
        icon:        DocumentSearchIcon,
        href:        '/queries/full-scan',
    },
    {
        name:        'NPC Vendor Item Scan',
        description: "Search for items sold by NPC Vendors which can be resold on the marketboard.",
        icon:        DocumentSearchIcon,
        href:        '/queries/full-scan',
    },
    {
        name:        'Beginner Out of Stock Scan',
        description: "Recommended for Beginners. No level requirement, high profit margins, low risk, low cost, low effort, low competition, but slow sale rates.",
        icon:        DocumentSearchIcon,
        href:        '/queries/full-scan',
    },
];
```

**Comment by Acen** [comment]
There are two ways to go about doing different field values/parameters.

1.) We use context.
This is how React recommends allowing prop values to change between parent/child stuff without drilling entire objects up and down the tree (which burns performance for a living).

2.) We use Redux.
This is how I'd probably recommend doing it, because we can use the entire state as a debuggable entity if something breaks.
Plus being able to push results back into redux means we can cache efficiently too, whilst keeping performance & data security consistent.

**Comment by cohenaj194** [comment]
> There are two ways to go about doing different (or modifying) field values/parameters.
> 
> 1.) We use context. This is how React recommends allowing prop values to change between parent/child stuff without drilling entire objects up and down the tree (which burns performance for a living).
> 
> 2.) We use Redux. This is how I'd probably recommend doing it, because we can use the entire state as a debuggable entity if something breaks. Plus being able to push results back into redux means we can cache efficiently too, whilst keeping performance & data security consistent.
> 
> Redux: https://react-redux.js.org/ https://redux-toolkit.js.org/ Context: https://reactjs.org/docs/context.html

Yep performance will be an issue down the line and it seems option 2 is better.

What is the time estimate to get either option going?

**Comment by Acen** [comment]
we'll use https://redux-toolkit.js.org/ to give an opinionated starting base.

Then it's just dirty modifying where the values are being loaded from for the form inputs and it'll be working in an MVP state.

So, not too long?

It'll really be if the table library likes that happening or not.
