### ISSUE TITLE
Add saddlebag link to teamcraft

### ISSUE THREAD

**Issue by cohenaj194** [ff14-advanced-market-search/saddlebag-with-pockets#311]
<img width="292" alt="image" src="https://github.com/ff14-advanced-market-search/saddlebag-with-pockets/assets/17516896/ce2b8414-68f7-44ee-ab1e-d89ca385678a">

I talked to the main teamcraft dev and they would like us to add a link in similar to universalis. 

Here are the 3 locations of these links in teamcraft:

- https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/blob/master/apps/client/src/app/modules/marketboard/marketboard-popup/marketboard-popup.component.html#L5
- https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/blob/master/apps/client/src/app/pages/db/item/item.component.ts#L449
- https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/blob/master/apps/client/src/app/pages/retainers/retainers/retainers.component.html#L95

we also need to add our icon in 
![chocobo](https://github.com/ff14-advanced-market-search/saddlebag-with-pockets/assets/17516896/9790e3cf-a1fc-4b1e-823f-4fc84be04777)

**Comment by jackoliver** [comment]
https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/pull/2723

**Comment by Acen** [comment]
Nice work. I wonder if it might be worth having someone do up a simpler logo for small usage. Fuzzy bird loses it shape at low resolutions.
