### ISSUE TITLE
Add region_wide option to ffxiv shopping list

### ISSUE THREAD

**Issue by cohenaj194** [ff14-advanced-market-search/saddlebag-with-pockets#320]
Theres a new `region_wide` option, this should be set to `false` by default.  Add it into the FE so that people can check it if they want to.

```
{
    "crafting_list": {
        ...
    },
    "home_server": "Famfrit",
    "region_wide": false
}
```

Just need to add something like this to the shopping list page
<img width="287" alt="image" src="https://github.com/ff14-advanced-market-search/saddlebag-with-pockets/assets/17516896/c49a6c87-fdca-4932-9221-ed44949349c2">

**Comment by oldben87** [comment]
Getting errors when trying to use this:

<img width="1424" alt="Screenshot 2023-09-23 at 10 55 29" src="https://github.com/ff14-advanced-market-search/saddlebag-with-pockets/assets/51456734/46f81848-cb51-455c-93ae-8009cbb8cde5">
