### ISSUE TITLE
Have shopping list display total_cost and average_cost_per_craft

### ISSUE THREAD

**Issue by cohenaj194** [ff14-advanced-market-search/saddlebag-with-pockets#322]
`total_cost` and `average_cost_per_craft` are fields that get included in the shopping list results. 

we should display them

i think the fix will go in here https://github.com/ff14-advanced-market-search/saddlebag-with-pockets/blob/master/app/routes/ffxiv.shopping-list.tsx

used for https://saddlebagexchange.com/ffxiv/shopping-list

**Comment by jackoliver** [comment]
missed this notif, i can pick this up.
