### ISSUE TITLE
Need to show exceptions from /api/recipelookup when using craftsim

### ISSUE THREAD

**Issue by cohenaj194** [ff14-advanced-market-search/saddlebag-with-pockets#329]
So theres a problem we are allowing users to go outside the given parameters of a search

<img width="699" alt="image" src="https://github.com/ff14-advanced-market-search/saddlebag-with-pockets/assets/17516896/3d984523-a1c3-463e-be84-07540ba673f8">

From the first api this results in the error

```
{
    "exception": "Median sale price and max_material_cost must be at least 100 gil"
}
```

However this is not displayed on the fe.  In fact not only can you select 0 (which you should not be able to do) but it also shows no error when you hit search. 

We need the exceptions from the first api to be displayed if `exception` is in the response.

**Comment by oldben87** [comment]
Have you got a list of min / max values for each of the inputs?
