### ISSUE TITLE
Add sale alert json to undercut generator

### ISSUE THREAD

**Issue by cohenaj194** [ff14-advanced-market-search/saddlebag-with-pockets#336]
For @fabiantorrestech

We can have the undercut generator also give the sale alert json.  The sale alert is very simple, just the `seller_id` an `server` we already have and then an empty list for `item_ids`

```
{
        "seller_id": "fasdfasdfasdfasdafadsfadfadfadf",
        "server": "Omega",
        "item_ids": []
}
```

**Comment by fabiantorrestech** [comment]
Hi, @cohenaj194 is this what we're looking for?

<img width="1396" alt="image" src="https://github.com/ff14-advanced-market-search/saddlebag-with-pockets/assets/46858378/5c8f4067-741f-4302-996d-f017d44da53e">

**Comment by fabiantorrestech** [comment]
Great, added the title and description to it

Just need to have it reviewed and create a PR (:
