### ISSUE TITLE
Maybe handle odd exceptions in verify_typing

### ISSUE THREAD

**Issue by cohenaj194** [ff14-advanced-market-search/saddlebag-with-pockets#354]
So the frontend doesnt handle exceptions when we find something in verify_typing.  This will produce a list of elements from whats wrong:

https://github.com/ff14-advanced-market-search/saddlebag-with-pockets/assets/17516896/931a2a01-5ab7-4d7e-b0a5-d1acf9722433

<img width="1083" alt="image" src="https://github.com/ff14-advanced-market-search/saddlebag-with-pockets/assets/17516896/7221c72d-54ec-4bfc-b10d-20a2952552f3">

<img width="1129" alt="image" src="https://github.com/ff14-advanced-market-search/saddlebag-with-pockets/assets/17516896/60b34597-a6f9-4f51-ba0c-8de0c4131d0c">

The frontend cant handle this and only shows a response when elements is a string

<img width="1133" alt="image" src="https://github.com/ff14-advanced-market-search/saddlebag-with-pockets/assets/17516896/0b233b2c-45ba-48fe-b8dc-b444a0332121">

However I'm not 100% sure we should have the FE tell people whats wrong, we dont want to point people in the right direction (i.e. tell people we are detecting their sql injection). Maybe if the elements is a list just tell people `This request is invalid, please screenshot your input and contact us on discord to resolve the issue.`

**Comment by oldben87** [comment]
If you changed the error response type then the front end will need updating.

Have you thought of changing the responses to be [REST](https://www.freecodecamp.org/news/rest-api-best-practices-rest-endpoint-design-examples/) responses?

**Comment by oldben87** [comment]
One thing we could do is uniform all responses to have a response of :
`{ success: true, data: {...} } 
{.success: false, error: string }`
Then you can have a dictionary of error strings you return.
And we can have a file we can reference and use and keep up to date:
`{ invalid_input: "Required input missing or wrongly formatted", default_error: "Unknown problem occurred",  }`
