### ISSUE TITLE
wow region keeps resetting 

### ISSUE THREAD

**Issue by cohenaj194** [ff14-advanced-market-search/saddlebag-with-pockets#390]
when you close out of your browser and reopen the wow region and server resets, we need to do something with cookies or how ffxiv does it so it saves properly

<img width="1290" alt="image" src="https://github.com/ff14-advanced-market-search/saddlebag-with-pockets/assets/17516896/f3a8a62f-1ce5-4c80-9b43-7a9a7c08a7ea">

**Comment by berickus** [comment]
<img width="1114" alt="Screenshot 2024-04-02 at 08 05 57" src="https://github.com/ff14-advanced-market-search/saddlebag-with-pockets/assets/3184026/c3d79b60-0a07-46a6-bd63-06a8cd83db77">
It seems the local storage is not updated once changed in the settings. During the existing session you stay in the selected region.

The issue only appears when the region and nothing else is changed. If you change the region and the server, it works.
