### ISSUE TITLE
Long form blog content

### ISSUE THREAD

**Issue by cohenaj194** [ff14-advanced-market-search/saddlebag-with-pockets#406]
# make blog posts

To index us better we need lots of text on a page

so we need to generate ai articles on "wow goldmaking using the auctionhouse" and "ffxiv gil making using the maketboard" and make sure it mentions "Saddlebag Exchange"

we can use this to help, the articles will be in markdown

https://app.simplified.com/ai

<img width="179" alt="image" src="https://github.com/ff14-advanced-market-search/saddlebag-with-pockets/assets/17516896/de37a784-6b9d-448d-b355-cbac31c16852">

# convert markdown to html

We can take all of the wiki guides and convert them using this: https://markdowntohtml.com/

# take html and make blog files

then we make blog pages like this, just take out the highlighted section and replace it with html:

https://github.com/ff14-advanced-market-search/saddlebag-with-pockets/blob/master/app/routes/blog.wow.tldr.tsx#L5-L108

raw page:

```
const WhateverRandomPageName = () => {
  return (
    <div className={`m-12`}>
      <main className="flex-1">
        ... random html goes here...
      </main>
    </div>
  )
}

export default WhateverRandomPageName
```

then just copy them over and make it `blog.$GAME.$NAME.tsx` and add them into https://github.com/ff14-advanced-market-search/saddlebag-with-pockets/blob/master/app/routes/blog._index.tsx#L5-L33

**Comment by helloabhii** [comment]
hey @cohenaj194 , i am working on it.
