### ISSUE TITLE
initial auto sort by profit amount does not work

### ISSUE THREAD

**Issue by cohenaj194** [ff14-advanced-market-search/saddlebag-with-pockets#64]
@Acen by default when the page loads in after getting results we should sort by profit amount.  Why does saddlebag initially sort by item id instead of by profit amount? It seems like this code block isnt working

https://github.com/ff14-advanced-market-search/saddlebag-with-pockets/blob/master/app/routes/queries/full-scan/Results.tsx#L157-L168

<img width="844" alt="image" src="https://user-images.githubusercontent.com/17516896/190898091-c3adf475-297f-44bb-83d0-aec697d1ae56.png">

**Comment by Acen** [comment]
This is the code that's setting the current sorting column:
https://github.com/ff14-advanced-market-search/saddlebag-with-pockets/blob/master/app/routes/queries/full-scan/Results.tsx#L157

It's likely that one of the if statements are failing and needs refining to.. not.. fail. 🤷

**Comment by cohenaj194** [comment]
So an alternative is to send the data out in a presorted array instead of a dictionary.  The api data seems to revert back to sorting by item id.  Instead I could fix the backend to include the `item_id` in the rows and then put all the rows in a `data` list like this:

```
{
    "data": [
        {
            "ROI": 36,
            "avg_ppu": 271662,
            "home_server_price": 375787,
            "home_update_time": "2022-10-27 02:55:29",
            "item_id": "37765",
            "npc_vendor_info": "",
            "ppu": 208227,
            "profit_amount": 138359,
            "profit_raw_percent": 63,
            "real_name": "Rinascita Poleyns of Fending",
            "sale_rates": "0.2903",
            "server": "Hyperion - Primal",
            "stack_size": 1,
            "update_time": "2022-10-27 08:35:58",
            "url": "https://universalis.app/market/37765"
        },
        {
            "ROI": 48,
            "avg_ppu": 245595,
            "home_server_price": 262317,
            "home_update_time": "2022-10-27 08:53:59",
            "item_id": "37792",
            "npc_vendor_info": "",
            "ppu": 115298,
            "profit_amount": 128138,
            "profit_raw_percent": 105,
            "real_name": "Rinascita Hood of Casting",
            "sale_rates": "0.2920",
            "server": "Leviathan - Primal",
            "stack_size": 1,
            "update_time": "2022-10-27 09:25:45",
            "url": "https://universalis.app/market/37792"
        }
]
```

The advantage is that we can decide how to sort this in the api, so out of stock will automatically come in sorted by lowest price per unit and all others will be sorted by profit amount. 

I have put up a test api cluster that can be reached here http://24.199.70.65/api/scan
