### ISSUE TITLE
clean up search query

### ISSUE THREAD

**Issue by cohenaj194** [ff14-advanced-market-search/saddlebag-with-pockets#97]
there are several parts of the scan query that we can fix

the filters needs to be a better dropdown, maybe something with check boxes like the mobile version would be better

<img width="357" alt="image" src="https://user-images.githubusercontent.com/17516896/197341446-1892c8e8-73a9-4229-aa65-f61bcb52ae15.png">

~~the npc vendor info should not show a link when an item has an empty string as its npc_vendor_info value, that means it is not a vendor item.~~ this one is done

<img width="181" alt="image" src="https://user-images.githubusercontent.com/17516896/197341613-3d66c76a-b5bc-4f09-a742-8451c66bf5b2.png">

we should also change the vendor png to this instead as right now its just reusing the universalis one 

<img width="73" alt="image" src="https://user-images.githubusercontent.com/17516896/197341990-6adb1834-032a-422f-89be-70c0701e04e0.png">

also in the vendor items we dont need to show the uuid there does not need to be text in the button it can be small

<img width="160" alt="image" src="https://user-images.githubusercontent.com/17516896/197342129-2b8f3426-56f3-4a29-bf0a-8dcf78a4cdd6.png">

we really need to fix the columns too, right now all the column titles are on one line, if we can put it on multiple lines that will make the table less wide

<img width="907" alt="image" src="https://user-images.githubusercontent.com/17516896/197342076-1d132985-09f0-41c2-ac7e-f95771b39440.png">

Out of stock items always show 0 as the home server price and 99999999999 as the profit amount.  Instead of 0 we should have the table say `No Listings` instead of 0 and `∞` instead of `99999999999` However the table should still read that in as `99999999999` behind the scenes so clicking the profit column always puts out of stock items at the top.

<img width="309" alt="image" src="https://user-images.githubusercontent.com/17516896/197341729-c15d0b99-4dd0-480f-873b-962b61692551.png">

**Comment by oldben87** [comment]
Do we have a png/svg of the meteor symbol?

**Comment by oldben87** [comment]
TODO notes for myself:

 - Make all buttons in form same size
 - Remove duplicated form code in all scan queries
 - New multi select form
